INSTALL_TARGET_PROCESSES = SpringBoard
ARCHS=arm64

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = BetterAppSwitcher

BetterAppSwitcher_FILES = Tweak.x
BetterAppSwitcher_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
