INSTALL_TARGET_PROCESSES = SpringBoard
ARCHS = arm64
PACKAGE_VERSION = 1.0
FINALPACKAGE = 1
FOR_RELEASE = 1

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = FolderCloserX

FolderCloserX_FILES = Tweak.x
FolderCloserX_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk